### ISSUE TITLE
Palaist

### ISSUE THREAD

**Issue by SharpHawks** [Kirlovon/Mykoob-API#3]
Sveiki, varētu kādu pamācību kā šo lietu varētu dabūt ejošu lapā? Neesmu spēcīgs node.js tāpēc prasu palīdzību. Visi faili stāv htdocs, samainīju login un password uz savu, bet ko tālāk un kā tālāk galīgi nav ne jausmas.

**Comment by Kirlovon** [comment]
Atvaino, ka neatbildēji uzreiz. 
Pareizi es saprotu, ka jūs vēlaties izmantot šo moduli PHP projektā? Tādā gadījumā izmantot šo moduli būs problemātiska, jo tā ir rakstīts uz TypeScript, lai izmantotu ar Node.js.
