### ISSUE TITLE
bro 

### ISSUE THREAD

**Issue by just-noname-bing** [Kirlovon/Mykoob-API#4]
Error: No school_user_id passed

    await api.authorize();

    const usersList = await api.getUsers();
 
    const lessonPlan = await api.lessonsPlan({
        from: Date.now() - 86400,
        to: Date.now(),
        school_classes_id: usersList[0].school_classes_id,
        school_user_id: usersList[0].school_user_id,
    });
 

    console.log(lessonsPlan)

========
                throw new Error(response.data.error.message);
                      ^

Error: No school_user_id passed
    at MykoobAPI.<anonymous> (C:\Users\user\node_modules\mykoob-api\lib\mykoobAPI.js:277:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\user\node_modules\mykoob-api\lib\mykoobAPI.js:4:58)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

====
npm 7.3.0 
node v15.5.1

**Comment by Kirlovon** [comment]
Broo, It looks like Mykoob has changed their API responses structure, but I don't have a working Mykoob account to check this. 
Anyway, you can try using this method: _(although it probably won't work)_
```ts
await api.authorize();

const user = await api.userData()

const lessonPlan = await api.lessonsPlan({
    from: Date.now() - 86400,
    to: Date.now(),
    school_classes_id: user.school_classes_id,
    school_user_id: user.school_user_id,
});

console.log(lessonsPlan)
``` 
Also, you can try logging into the [mobile version of the Mykoob](https://m.mykoob.lv/), if you fail, maybe your account is somehow limited.
I do not plan to support this library, so if you find fix, feel free to make a pull request.
